# Generated by Django 4.2.7 on 2023-11-22 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Рост')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес')),
                ('neck', models.IntegerField(blank=True, null=True, verbose_name='Шея')),
                ('hands', models.IntegerField(blank=True, null=True, verbose_name='Руки')),
                ('forearms', models.IntegerField(blank=True, null=True, verbose_name='Предплечья')),
                ('chest', models.IntegerField(blank=True, null=True, verbose_name='Грудь')),
                ('waist', models.IntegerField(blank=True, null=True, verbose_name='Талия')),
                ('pelvis', models.IntegerField(blank=True, null=True, verbose_name='Таз')),
                ('hips', models.IntegerField(blank=True, null=True, verbose_name='Бедра')),
                ('shin', models.IntegerField(blank=True, null=True, verbose_name='Голень')),
                ('ankles', models.IntegerField(blank=True, null=True, verbose_name='Лодыжки')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
