# Generated by Django 4.2.7 on 2023-11-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='user',
        ),
    ]
