# Generated by Django 4.2.7 on 2023-12-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_aboniment_anons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aboniment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.aboniment'),
        ),
    ]
