# Generated by Django 4.2.7 on 2023-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_aboniment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboniment',
            name='buy_day',
            field=models.CharField(default='', max_length=15, verbose_name='Дата приобретения'),
        ),
    ]
