# Generated by Django 4.2.7 on 2023-12-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_aboniment_buy_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboniment',
            name='buy_day',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buy_day',
            field=models.CharField(default='', max_length=15, verbose_name='Дата приобретения'),
        ),
    ]
