# Generated by Django 4.2.7 on 2023-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_aboniment_buy_day_userprofile_buy_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target',
            field=models.CharField(default='', max_length=50, verbose_name='Цель'),
        ),
    ]
