# Generated by Django 4.2.7 on 2023-12-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='target',
        ),
        migrations.AddField(
            model_name='params',
            name='target',
            field=models.CharField(default='', max_length=50, verbose_name='Цель'),
        ),
    ]
