# Generated by Django 4.2.7 on 2023-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_target_params_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='ankles',
            field=models.FloatField(blank=True, null=True, verbose_name='Лодыжки'),
        ),
        migrations.AlterField(
            model_name='params',
            name='chest',
            field=models.FloatField(blank=True, null=True, verbose_name='Грудь'),
        ),
        migrations.AlterField(
            model_name='params',
            name='forearms',
            field=models.FloatField(blank=True, null=True, verbose_name='Предплечья'),
        ),
        migrations.AlterField(
            model_name='params',
            name='hands',
            field=models.FloatField(blank=True, null=True, verbose_name='Руки'),
        ),
        migrations.AlterField(
            model_name='params',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='params',
            name='hips',
            field=models.FloatField(blank=True, null=True, verbose_name='Бедра'),
        ),
        migrations.AlterField(
            model_name='params',
            name='neck',
            field=models.FloatField(blank=True, null=True, verbose_name='Шея'),
        ),
        migrations.AlterField(
            model_name='params',
            name='pelvis',
            field=models.FloatField(blank=True, null=True, verbose_name='Таз'),
        ),
        migrations.AlterField(
            model_name='params',
            name='shin',
            field=models.FloatField(blank=True, null=True, verbose_name='Голень'),
        ),
        migrations.AlterField(
            model_name='params',
            name='waist',
            field=models.FloatField(blank=True, null=True, verbose_name='Талия'),
        ),
        migrations.AlterField(
            model_name='params',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
