# Generated by Django 4.2.7 on 2023-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_params_ankles_alter_params_chest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='target',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Цель'),
        ),
    ]
