# Generated by Django 4.2.7 on 2023-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.CharField(max_length=15, verbose_name='Цена')),
                ('anons', models.CharField(max_length=500, verbose_name='Описание абонимента')),
            ],
            options={
                'verbose_name': 'Абонимент',
                'verbose_name_plural': 'Абонименты',
            },
        ),
        migrations.CreateModel(
            name='AboutGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название зоны')),
                ('anons', models.CharField(max_length=500, verbose_name='Тренажеры')),
            ],
            options={
                'verbose_name': 'О зале',
                'verbose_name_plural': 'О зале',
            },
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('obj_title', models.CharField(max_length=50, verbose_name='направление')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
